correct_answer(cfu_1, 'dog').
correct_answer(cfu_2, 'chickie').
correct_answer(cfu_2, 'chick').
correct_answer(cfu_3, 'duck').
correct_answer(cfu_4, 'cup').
correct_answer(cfu_5, 'hammer').
correct_answer(cfu_6, 'shoe').
correct_answer(cfu_7, 'frog').
correct_answer(cfu_8, 'butterfly').